sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="kinetic"
    - CI_ROS_DISTRO="melodic"

install:
  - docker build -t basler_tof_$CI_ROS_DISTRO -f Dockerfile-$CI_ROS_DISTRO .

script:
  - docker run basler_tof_$CI_ROS_DISTRO /bin/bash -c "source devel/setup.bash && catkin run_tests && catkin_test_results"
